resources:
- ../default
patches:
- path: manager_webhook_patch.yaml
  target:
    kind: Deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: manager
  newName: localhost:5001/victoriametrics/operator
  newTag: heads-master-0-gbdcaa7d-dirty-03fd4b9c
