/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/VictoriaMetrics/operator/api/client/versioned/scheme"
	v1beta1 "github.com/VictoriaMetrics/operator/api/core/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VMSinglesGetter has a method to return a VMSingleInterface.
// A group's client should implement this interface.
type VMSinglesGetter interface {
	VMSingles(namespace string) VMSingleInterface
}

// VMSingleInterface has methods to work with VMSingle resources.
type VMSingleInterface interface {
	Create(ctx context.Context, vMSingle *v1beta1.VMSingle, opts v1.CreateOptions) (*v1beta1.VMSingle, error)
	Update(ctx context.Context, vMSingle *v1beta1.VMSingle, opts v1.UpdateOptions) (*v1beta1.VMSingle, error)
	UpdateStatus(ctx context.Context, vMSingle *v1beta1.VMSingle, opts v1.UpdateOptions) (*v1beta1.VMSingle, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VMSingle, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VMSingleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMSingle, err error)
	VMSingleExpansion
}

// vMSingles implements VMSingleInterface
type vMSingles struct {
	client rest.Interface
	ns     string
}

// newVMSingles returns a VMSingles
func newVMSingles(c *CoreV1beta1Client, namespace string) *vMSingles {
	return &vMSingles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vMSingle, and returns the corresponding vMSingle object, and an error if there is any.
func (c *vMSingles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VMSingle, err error) {
	result = &v1beta1.VMSingle{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmsingles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VMSingles that match those selectors.
func (c *vMSingles) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VMSingleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VMSingleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmsingles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vMSingles.
func (c *vMSingles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vmsingles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vMSingle and creates it.  Returns the server's representation of the vMSingle, and an error, if there is any.
func (c *vMSingles) Create(ctx context.Context, vMSingle *v1beta1.VMSingle, opts v1.CreateOptions) (result *v1beta1.VMSingle, err error) {
	result = &v1beta1.VMSingle{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vmsingles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMSingle).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vMSingle and updates it. Returns the server's representation of the vMSingle, and an error, if there is any.
func (c *vMSingles) Update(ctx context.Context, vMSingle *v1beta1.VMSingle, opts v1.UpdateOptions) (result *v1beta1.VMSingle, err error) {
	result = &v1beta1.VMSingle{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmsingles").
		Name(vMSingle.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMSingle).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vMSingles) UpdateStatus(ctx context.Context, vMSingle *v1beta1.VMSingle, opts v1.UpdateOptions) (result *v1beta1.VMSingle, err error) {
	result = &v1beta1.VMSingle{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmsingles").
		Name(vMSingle.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMSingle).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vMSingle and deletes it. Returns an error if one occurs.
func (c *vMSingles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmsingles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vMSingles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmsingles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vMSingle.
func (c *vMSingles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMSingle, err error) {
	result = &v1beta1.VMSingle{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vmsingles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
