/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1 "github.com/VictoriaMetrics/operator/api/operator/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VLAgentInformer provides access to a shared informer and lister for
// VLAgents. Prefer using the type-safe variant (see [TypedVLAgentInformer]).
type VLAgentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1.VLAgentLister
}

// TypedVLAgentInformer provides access to a shared informer and lister for
// VLAgents, including the type-safe TypedInformer variant.
// It is a superset of VLAgentInformer.
type TypedVLAgentInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VLAgentIndexInformer
	Lister() operatorv1.VLAgentLister
}

// VLAgentIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VLAgentIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1.VLAgent]

// VLAgentHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VLAgent.
type VLAgentHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1.VLAgent]

// VLAgentDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VLAgent.
type VLAgentDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1.VLAgent]

// VLAgentFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VLAgent.
type VLAgentFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1.VLAgent]

// VLAgentIndexers is a specialization of [cache.TypedIndexers] for VLAgent.
type VLAgentIndexers = cache.TypedIndexers[*apioperatorv1.VLAgent]

// DeletedVLAgent is a specialization of [cache.DeletedObject] for VLAgent.
type DeletedVLAgent = cache.DeletedObject[*apioperatorv1.VLAgent]

type vLAgentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVLAgentInformer constructs a new informer for VLAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVLAgentInformer]).
func NewVLAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVLAgentInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVLAgentInformer constructs a new informer for VLAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVLAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VLAgentIndexers) VLAgentIndexInformer {
	return NewTypedVLAgentInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVLAgentInformer constructs a new informer for VLAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVLAgentInformer]).
func NewFilteredVLAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVLAgentInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVLAgentInformer constructs a new informer for VLAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVLAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VLAgentIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VLAgentIndexInformer {
	return NewTypedVLAgentInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVLAgentInformerWithOptions constructs a new informer for VLAgent type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVLAgentInformerWithOptions]).
func NewVLAgentInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVLAgentInformerWithOptions(client, namespace, options)
}

// NewTypedVLAgentInformerWithOptions constructs a new informer for VLAgent type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVLAgentInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VLAgentIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1", Resource: "vlagents"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1.VLAgent](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1().VLAgents(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1().VLAgents(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1().VLAgents(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1().VLAgents(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1.VLAgent{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vLAgentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVLAgentInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vLAgentInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vLAgentInformer) TypedInformer() VLAgentIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1.VLAgent](f.factory.InformerFor(&apioperatorv1.VLAgent{}, f.defaultInformer))
}

func (f *vLAgentInformer) Lister() operatorv1.VLAgentLister {
	return operatorv1.NewVLAgentLister(f.Informer().GetIndexer())
}

// ToTypedVLAgentInformer converts an untyped informer into a TypedVLAgentInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VLAgent. If that is not the case, calling type-safe methods of the returned
// TypedVLAgentInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVLAgentInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVLAgentInformer(informer VLAgentInformer) TypedVLAgentInformer {
	if informer, ok := informer.(TypedVLAgentInformer); ok {
		return informer
	}
	return &vLAgentTypedInformerAdapter{informer}
}

type vLAgentTypedInformerAdapter struct {
	VLAgentInformer
}

func (a *vLAgentTypedInformerAdapter) TypedInformer() VLAgentIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1.VLAgent](a.Informer())
}

// ToVLAgentIndexInformer converts an untyped informer into a VLAgentIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VLAgent. If that is not the case, calling type-safe methods of the returned
// VLAgentIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VLAgentIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVLAgentIndexInformer(informer cache.SharedIndexInformer) VLAgentIndexInformer {
	if informer, ok := informer.(VLAgentIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1.VLAgent](informer)
}
