name: Publish Reports
description: Publish JUnit test report

runs:
  using: composite
  steps:
    - name: Publish Test Report
      if: success() || failure()
      uses: mikepenz/action-junit-report@3a81627bfac62268172037048872e8ebd4207e6d  # v6.4.1
      with:
        report_paths: 'report.xml'
