/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen-v0.32. DO NOT EDIT.

package v1

import (
	context "context"

	scheme "github.com/VictoriaMetrics/operator/api/client/versioned/scheme"
	operatorv1 "github.com/VictoriaMetrics/operator/api/operator/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VMAnomaliesGetter has a method to return a VMAnomalyInterface.
// A group's client should implement this interface.
type VMAnomaliesGetter interface {
	VMAnomalies(namespace string) VMAnomalyInterface
}

// VMAnomalyInterface has methods to work with VMAnomaly resources.
type VMAnomalyInterface interface {
	Create(ctx context.Context, vMAnomaly *operatorv1.VMAnomaly, opts metav1.CreateOptions) (*operatorv1.VMAnomaly, error)
	Update(ctx context.Context, vMAnomaly *operatorv1.VMAnomaly, opts metav1.UpdateOptions) (*operatorv1.VMAnomaly, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vMAnomaly *operatorv1.VMAnomaly, opts metav1.UpdateOptions) (*operatorv1.VMAnomaly, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*operatorv1.VMAnomaly, error)
	List(ctx context.Context, opts metav1.ListOptions) (*operatorv1.VMAnomalyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *operatorv1.VMAnomaly, err error)
	VMAnomalyExpansion
}

// vMAnomalies implements VMAnomalyInterface
type vMAnomalies struct {
	*gentype.ClientWithList[*operatorv1.VMAnomaly, *operatorv1.VMAnomalyList]
}

// newVMAnomalies returns a VMAnomalies
func newVMAnomalies(c *OperatorV1Client, namespace string) *vMAnomalies {
	return &vMAnomalies{
		gentype.NewClientWithList[*operatorv1.VMAnomaly, *operatorv1.VMAnomalyList](
			"vmanomalies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operatorv1.VMAnomaly { return &operatorv1.VMAnomaly{} },
			func() *operatorv1.VMAnomalyList { return &operatorv1.VMAnomalyList{} },
		),
	}
}
