namespace: vm
resources:
- ../default
- ../webhook
- ../certmanager
patches:
- path: manager_webhook_patch.yaml
  target:
    kind: Deployment
replacements:
- source:
    fieldPath: .metadata.name
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      create: true
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      version: v1
- source:
    fieldPath: .metadata.namespace
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      create: true
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      version: v1
