- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --webhook.enable
- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    containerPort: 9443
    name: webhook-server
    protocol: TCP
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --webhook.certDir=/tmp/k8s-webhook-server/serving-certs
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /tmp/k8s-webhook-server/serving-certs
    name: webhook-certs
    readOnly: true
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: webhook-certs
    secret:
      secretName: webhook-server-cert
