- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --metrics-bind-address=:8443
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /tmp/k8s-metrics-server/metrics-certs
    name: metrics-certs
    readOnly: true
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --tls.certDir=/tmp/k8s-metrics-server/metrics-certs
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: metrics-certs
    secret:
      secretName: metrics-server-cert
      optional: false
      items:
        - key: ca.crt
          path: ca.crt
        - key: tls.crt
          path: tls.crt
        - key: tls.key
          path: tls.key
