apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: vm
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: victoria-metrics-operator
