/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.35. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/VictoriaMetrics/operator/api/operator/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VMDistributedLister helps list VMDistributed.
// All objects returned here must be treated as read-only.
type VMDistributedLister interface {
	// List lists all VMDistributed in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.VMDistributed, err error)
	// VMDistributed returns an object that can list and get VMDistributed.
	VMDistributed(namespace string) VMDistributedNamespaceLister
	VMDistributedListerExpansion
}

// vMDistributedLister implements the VMDistributedLister interface.
type vMDistributedLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.VMDistributed]
}

// NewVMDistributedLister returns a new VMDistributedLister.
func NewVMDistributedLister(indexer cache.Indexer) VMDistributedLister {
	return &vMDistributedLister{listers.New[*operatorv1alpha1.VMDistributed](indexer, operatorv1alpha1.Resource("vmdistributed"))}
}

// VMDistributed returns an object that can list and get VMDistributed.
func (s *vMDistributedLister) VMDistributed(namespace string) VMDistributedNamespaceLister {
	return vMDistributedNamespaceLister{listers.NewNamespaced[*operatorv1alpha1.VMDistributed](s.ResourceIndexer, namespace)}
}

// VMDistributedNamespaceLister helps list and get VMDistributed.
// All objects returned here must be treated as read-only.
type VMDistributedNamespaceLister interface {
	// List lists all VMDistributed in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.VMDistributed, err error)
	// Get retrieves the VMDistributed from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.VMDistributed, error)
	VMDistributedNamespaceListerExpansion
}

// vMDistributedNamespaceLister implements the VMDistributedNamespaceLister
// interface.
type vMDistributedNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.VMDistributed]
}
