/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/VictoriaMetrics/operator/api/core/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVMServiceScrapes implements VMServiceScrapeInterface
type FakeVMServiceScrapes struct {
	Fake *FakeCoreV1beta1
	ns   string
}

var vmservicescrapesResource = schema.GroupVersionResource{Group: "", Version: "v1beta1", Resource: "vmservicescrapes"}

var vmservicescrapesKind = schema.GroupVersionKind{Group: "", Version: "v1beta1", Kind: "VMServiceScrape"}

// Get takes name of the vMServiceScrape, and returns the corresponding vMServiceScrape object, and an error if there is any.
func (c *FakeVMServiceScrapes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VMServiceScrape, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vmservicescrapesResource, c.ns, name), &v1beta1.VMServiceScrape{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VMServiceScrape), err
}

// List takes label and field selectors, and returns the list of VMServiceScrapes that match those selectors.
func (c *FakeVMServiceScrapes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VMServiceScrapeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vmservicescrapesResource, vmservicescrapesKind, c.ns, opts), &v1beta1.VMServiceScrapeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.VMServiceScrapeList{ListMeta: obj.(*v1beta1.VMServiceScrapeList).ListMeta}
	for _, item := range obj.(*v1beta1.VMServiceScrapeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vMServiceScrapes.
func (c *FakeVMServiceScrapes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vmservicescrapesResource, c.ns, opts))

}

// Create takes the representation of a vMServiceScrape and creates it.  Returns the server's representation of the vMServiceScrape, and an error, if there is any.
func (c *FakeVMServiceScrapes) Create(ctx context.Context, vMServiceScrape *v1beta1.VMServiceScrape, opts v1.CreateOptions) (result *v1beta1.VMServiceScrape, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vmservicescrapesResource, c.ns, vMServiceScrape), &v1beta1.VMServiceScrape{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VMServiceScrape), err
}

// Update takes the representation of a vMServiceScrape and updates it. Returns the server's representation of the vMServiceScrape, and an error, if there is any.
func (c *FakeVMServiceScrapes) Update(ctx context.Context, vMServiceScrape *v1beta1.VMServiceScrape, opts v1.UpdateOptions) (result *v1beta1.VMServiceScrape, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vmservicescrapesResource, c.ns, vMServiceScrape), &v1beta1.VMServiceScrape{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VMServiceScrape), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVMServiceScrapes) UpdateStatus(ctx context.Context, vMServiceScrape *v1beta1.VMServiceScrape, opts v1.UpdateOptions) (*v1beta1.VMServiceScrape, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vmservicescrapesResource, "status", c.ns, vMServiceScrape), &v1beta1.VMServiceScrape{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VMServiceScrape), err
}

// Delete takes name of the vMServiceScrape and deletes it. Returns an error if one occurs.
func (c *FakeVMServiceScrapes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vmservicescrapesResource, c.ns, name, opts), &v1beta1.VMServiceScrape{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVMServiceScrapes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vmservicescrapesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.VMServiceScrapeList{})
	return err
}

// Patch applies the patch and returns the patched vMServiceScrape.
func (c *FakeVMServiceScrapes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMServiceScrape, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vmservicescrapesResource, c.ns, name, pt, data, subresources...), &v1beta1.VMServiceScrape{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VMServiceScrape), err
}
