/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen-v0.31. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVMPodScrapes implements VMPodScrapeInterface
type FakeVMPodScrapes struct {
	Fake *FakeOperatorV1beta1
	ns   string
}

var vmpodscrapesResource = v1beta1.SchemeGroupVersion.WithResource("vmpodscrapes")

var vmpodscrapesKind = v1beta1.SchemeGroupVersion.WithKind("VMPodScrape")

// Get takes name of the vMPodScrape, and returns the corresponding vMPodScrape object, and an error if there is any.
func (c *FakeVMPodScrapes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VMPodScrape, err error) {
	emptyResult := &v1beta1.VMPodScrape{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(vmpodscrapesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMPodScrape), err
}

// List takes label and field selectors, and returns the list of VMPodScrapes that match those selectors.
func (c *FakeVMPodScrapes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VMPodScrapeList, err error) {
	emptyResult := &v1beta1.VMPodScrapeList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(vmpodscrapesResource, vmpodscrapesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.VMPodScrapeList{ListMeta: obj.(*v1beta1.VMPodScrapeList).ListMeta}
	for _, item := range obj.(*v1beta1.VMPodScrapeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vMPodScrapes.
func (c *FakeVMPodScrapes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(vmpodscrapesResource, c.ns, opts))

}

// Create takes the representation of a vMPodScrape and creates it.  Returns the server's representation of the vMPodScrape, and an error, if there is any.
func (c *FakeVMPodScrapes) Create(ctx context.Context, vMPodScrape *v1beta1.VMPodScrape, opts v1.CreateOptions) (result *v1beta1.VMPodScrape, err error) {
	emptyResult := &v1beta1.VMPodScrape{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(vmpodscrapesResource, c.ns, vMPodScrape, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMPodScrape), err
}

// Update takes the representation of a vMPodScrape and updates it. Returns the server's representation of the vMPodScrape, and an error, if there is any.
func (c *FakeVMPodScrapes) Update(ctx context.Context, vMPodScrape *v1beta1.VMPodScrape, opts v1.UpdateOptions) (result *v1beta1.VMPodScrape, err error) {
	emptyResult := &v1beta1.VMPodScrape{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(vmpodscrapesResource, c.ns, vMPodScrape, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMPodScrape), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVMPodScrapes) UpdateStatus(ctx context.Context, vMPodScrape *v1beta1.VMPodScrape, opts v1.UpdateOptions) (result *v1beta1.VMPodScrape, err error) {
	emptyResult := &v1beta1.VMPodScrape{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(vmpodscrapesResource, "status", c.ns, vMPodScrape, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMPodScrape), err
}

// Delete takes name of the vMPodScrape and deletes it. Returns an error if one occurs.
func (c *FakeVMPodScrapes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vmpodscrapesResource, c.ns, name, opts), &v1beta1.VMPodScrape{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVMPodScrapes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(vmpodscrapesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.VMPodScrapeList{})
	return err
}

// Patch applies the patch and returns the patched vMPodScrape.
func (c *FakeVMPodScrapes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMPodScrape, err error) {
	emptyResult := &v1beta1.VMPodScrape{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(vmpodscrapesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMPodScrape), err
}
