/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen-v0.31. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVMProbes implements VMProbeInterface
type FakeVMProbes struct {
	Fake *FakeOperatorV1beta1
	ns   string
}

var vmprobesResource = v1beta1.SchemeGroupVersion.WithResource("vmprobes")

var vmprobesKind = v1beta1.SchemeGroupVersion.WithKind("VMProbe")

// Get takes name of the vMProbe, and returns the corresponding vMProbe object, and an error if there is any.
func (c *FakeVMProbes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VMProbe, err error) {
	emptyResult := &v1beta1.VMProbe{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(vmprobesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMProbe), err
}

// List takes label and field selectors, and returns the list of VMProbes that match those selectors.
func (c *FakeVMProbes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VMProbeList, err error) {
	emptyResult := &v1beta1.VMProbeList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(vmprobesResource, vmprobesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.VMProbeList{ListMeta: obj.(*v1beta1.VMProbeList).ListMeta}
	for _, item := range obj.(*v1beta1.VMProbeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vMProbes.
func (c *FakeVMProbes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(vmprobesResource, c.ns, opts))

}

// Create takes the representation of a vMProbe and creates it.  Returns the server's representation of the vMProbe, and an error, if there is any.
func (c *FakeVMProbes) Create(ctx context.Context, vMProbe *v1beta1.VMProbe, opts v1.CreateOptions) (result *v1beta1.VMProbe, err error) {
	emptyResult := &v1beta1.VMProbe{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(vmprobesResource, c.ns, vMProbe, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMProbe), err
}

// Update takes the representation of a vMProbe and updates it. Returns the server's representation of the vMProbe, and an error, if there is any.
func (c *FakeVMProbes) Update(ctx context.Context, vMProbe *v1beta1.VMProbe, opts v1.UpdateOptions) (result *v1beta1.VMProbe, err error) {
	emptyResult := &v1beta1.VMProbe{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(vmprobesResource, c.ns, vMProbe, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMProbe), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVMProbes) UpdateStatus(ctx context.Context, vMProbe *v1beta1.VMProbe, opts v1.UpdateOptions) (result *v1beta1.VMProbe, err error) {
	emptyResult := &v1beta1.VMProbe{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(vmprobesResource, "status", c.ns, vMProbe, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMProbe), err
}

// Delete takes name of the vMProbe and deletes it. Returns an error if one occurs.
func (c *FakeVMProbes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vmprobesResource, c.ns, name, opts), &v1beta1.VMProbe{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVMProbes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(vmprobesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.VMProbeList{})
	return err
}

// Patch applies the patch and returns the patched vMProbe.
func (c *FakeVMProbes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMProbe, err error) {
	emptyResult := &v1beta1.VMProbe{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(vmprobesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.VMProbe), err
}
