kind: ConfigMap
apiVersion: v1
metadata:
  name: vm-agent-global-relabel-config
  labels:
    app: vm-operator
data:
  relabel.yaml: |-
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: pod_name

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vm-agent-url-relabel-config
  labels:
    app: vm-operator
data:
  relabel.yaml: |-
    - source_labels: [__meta_kubernetes_node_name]
      target_label: node_name
---
apiVersion: v1
kind: Secret
metadata:
  name: rws-bearer-token
  labels:
    app: vm-operator
type: Opaque
stringData:
  token: token_test
---
apiVersion: v1
kind: Secret
metadata:
  name: rws-basic-auth
  labels:
    app: vm-operator
type: Opaque
stringData:
  username: adm"in,aa
  password: passw0rd
---
apiVersion: victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  # Add fields here
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
  serviceAccountName: vmagent
  additionalArgs:
    memory.allowedPercent: "40"
  relabelConfig:
    name: "vm-agent-global-relabel-config"
    key: "relabel.yaml"
  flushInterval: 2s
  queues: 2
  maxDiskUsagePerURL: 33
  sendTimeout: 30s
  showURL: true
  label:
    primary: "yes"
    secondary: "yes"
  remoteWrite:
    - url: "http://vmsingle-example-vmsingle.default.svc:8429/api/v1/write"
      basicAuth:
        username:
          name: rws-basic-auth
          key: username
        password:
          name: rws-basic-auth
          key: password
      urlRelabelConfig:
        name: "vm-agent-url-relabel-config"
        key: "relabel.yaml"

    - url: "http://vmsingle-example-vmsingle.alternative.svc:8429/api/v1/write"
      bearerTokenSecret:
        name: rws-bearer-token
        key: token
      urlRelabelConfig:
        name: "vm-agent-global-relabel-config"
        key: "relabel.yaml"