apiVersion: victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  # Add fields here
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
  serviceAccountName: vmagent
  additionalArgs:
    memory.allowedPercent: "40"
  relabelConfig:
    name: "vm-agent-global-relabel-config"
    key: "relabel.yaml"
  remoteWrite:
    - url: "http://vmsingle-example-vmsingle.default.svc:8429/api/v1/write"
      basicAuth:
        username:
          name: rws-basic-auth
          key: username
        password:
          name: rws-basic-auth
          key: password
      queues: 2
      urlRelabelConfig:
        name: "vm-agent-url-relabel-config"
        key: "relabel.yaml"
      label:
        primary: "yes"
    - url: "http://vmsingle-example-vmsingle.alternative.svc:8429/api/v1/write"
      flushInterval: 2m
      maxDiskUsagePerURL: 33
      sendTimeout: 10m
      showURL: true
      urlRelabelConfig:
        name: "vm-agent-global-relabel-config"
        key: "relabel.yaml"
      label:
        secondary: "yes"