# permissions for end users to view vmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-vmcluster-viewer
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmclusters/status
  verbs:
  - get
