# permissions for end users to edit vlogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-vlogs-editor-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vlogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vlogs/status
  verbs:
  - get
