# permissions for end users to edit vmalertmanagerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-vmalertmanagerconfig-editor
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmalertmanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmalertmanagerconfigs/status
  verbs:
  - get
