# permissions for end users to view vmnodescrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-vmnodescrape-viewer
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmnodescrapes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmnodescrapes/status
  verbs:
  - get
