# permissions for end users to edit vmalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-vmalert-editor
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmalerts/status
  verbs:
  - get
