# This rule is not used by the project victoriametrics-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to operator.victoriametrics.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-VMDistributedCluster-viewer-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - VMDistributedClusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - VMDistributedClusters/status
  verbs:
  - get
