apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vm-operator-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostNetwork: false
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - emptyDir
    - configMap
    - projected
    - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-operator-psp-role
rules:
  - apiGroups:
      - "policy"
    resourceNames:
      - vm-operator-psp
    resources:
      - podsecuritypolicies
    verbs:
      - 'use'

