---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
- nonResourceURLs:
  - /metrics
  - /metrics/resources
  - /metrics/slis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  - persistentvolumeclaims/finalizers
  - secrets/finalizers
  - serviceaccounts/finalizers
  - services/finalizers
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - events
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/finalizers
  - deployments/finalizers
  - statefulsets/finalizers
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.openshift.io
  - route.openshift.io
  resources:
  - registry/metrics
  - routers/metrics
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  - podmonitors
  - probes
  - prometheusrules
  - scrapeconfigs
  - servicemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs/status
  - podmonitors/status
  - probes/status
  - prometheusrules/status
  - scrapeconfigs/status
  - servicemonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  - networkpolicies/finalizers
  verbs:
  - patch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vlagents
  - vlclusters
  - vldistributed
  - vlogs
  - vlsingles
  - vmagents
  - vmalertmanagerconfigs
  - vmalertmanagers
  - vmalerts
  - vmanomalies
  - vmanomalyconfigs
  - vmauths
  - vmclusters
  - vmdistributed
  - vmnodescrapes
  - vmpodscrapes
  - vmprobes
  - vmrules
  - vmscrapeconfigs
  - vmservicescrapes
  - vmsingles
  - vmstaticscrapes
  - vmusers
  - vtagents
  - vtclusters
  - vtsingles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vlagents/finalizers
  - vlclusters/finalizers
  - vldistributed/finalizers
  - vlogs/finalizers
  - vlsingles/finalizers
  - vmagents/finalizers
  - vmalertmanagerconfigs/finalizers
  - vmalertmanagers/finalizers
  - vmalerts/finalizers
  - vmanomalies/finalizers
  - vmauths/finalizers
  - vmclusters/finalizers
  - vmdistributed/finalizers
  - vmnodescrapes/finalizers
  - vmpodscrapes/finalizers
  - vmprobes/finalizers
  - vmrules/finalizers
  - vmscrapeconfigs/finalizers
  - vmservicescrapes/finalizers
  - vmsingles/finalizers
  - vmstaticscrapes/finalizers
  - vmusers/finalizers
  - vtagents/finalizers
  - vtclusters/finalizers
  - vtsingles/finalizers
  verbs:
  - patch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vlagents/status
  - vlclusters/status
  - vldistributed/status
  - vlogs/status
  - vlsingles/status
  - vmagents/status
  - vmalertmanagerconfigs/status
  - vmalertmanagers/status
  - vmalerts/status
  - vmanomalies/status
  - vmanomalyconfigs/status
  - vmauths/status
  - vmclusters/status
  - vmdistributed/status
  - vmnodescrapes/status
  - vmpodscrapes/status
  - vmprobes/status
  - vmrules/status
  - vmscrapeconfigs/status
  - vmservicescrapes/status
  - vmsingles/status
  - vmstaticscrapes/status
  - vmusers/status
  - vtagents/status
  - vtclusters/status
  - vtsingles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/finalizers
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings/finalizers
  - clusterroles/finalizers
  verbs:
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
