---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vlogs
  - vlogs/finalizers
  - vlogs/status
  - vlsingles
  - vlsingles/finalizers
  - vlsingles/status
  - vlclusters
  - vlclusters/finalizers
  - vlclusters/status
  - vmagents
  - vmagents/finalizers
  - vmagents/status
  - vmalertmanagerconfigs
  - vmalertmanagerconfigs/finalizers
  - vmalertmanagerconfigs/status
  - vmalertmanagers
  - vmalertmanagers/finalizers
  - vmalertmanagers/status
  - vmalerts
  - vmalerts/finalizers
  - vmalerts/status
  - vmauths
  - vmauths/finalizers
  - vmauths/status
  - vmclusters
  - vmclusters/finalizers
  - vmclusters/status
  - vmnodescrapes
  - vmnodescrapes/finalizers
  - vmnodescrapes/status
  - vmpodscrapes
  - vmpodscrapes/finalizers
  - vmpodscrapes/status
  - vmprobes
  - vmprobes/finalizers
  - vmprobes/status
  - vmrules
  - vmrules/finalizers
  - vmrules/status
  - vmscrapeconfigs
  - vmscrapeconfigs/finalizers
  - vmscrapeconfigs/status
  - vmservicescrapes
  - vmservicescrapes/finalizers
  - vmservicescrapes/status
  - vmsingles
  - vmsingles/finalizers
  - vmsingles/status
  - vmstaticscrapes
  - vmstaticscrapes/finalizers
  - vmstaticscrapes/status
  - vmusers
  - vmusers/finalizers
  - vmusers/status
  - vmanomalies
  - vmanomalies/finalizers
  - vmanomalies/status
  verbs:
  - get
  - patch
  - update
