# permissions for end users to view vmauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmauth-viewer-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmauths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmauths/status
  verbs:
  - get
