# permissions for end users to edit vmauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmauth-editor-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmauths/status
  verbs:
  - get
