# permissions for end users to view vmnodescrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmnodescrape-viewer-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmnodescrapes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmnodescrapes/status
  verbs:
  - get
