# permissions for end users to edit vmrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmrule-editor-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmrules/status
  verbs:
  - get
