# permissions for end users to view vmusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmuser-viewer-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmusers/status
  verbs:
  - get
