/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VMAgents returns a VMAgentInformer.
	VMAgents() VMAgentInformer
	// VMAlerts returns a VMAlertInformer.
	VMAlerts() VMAlertInformer
	// VMAlertmanagers returns a VMAlertmanagerInformer.
	VMAlertmanagers() VMAlertmanagerInformer
	// VMAlertmanagerConfigs returns a VMAlertmanagerConfigInformer.
	VMAlertmanagerConfigs() VMAlertmanagerConfigInformer
	// VMAuths returns a VMAuthInformer.
	VMAuths() VMAuthInformer
	// VMClusters returns a VMClusterInformer.
	VMClusters() VMClusterInformer
	// VMNodeScrapes returns a VMNodeScrapeInformer.
	VMNodeScrapes() VMNodeScrapeInformer
	// VMPodScrapes returns a VMPodScrapeInformer.
	VMPodScrapes() VMPodScrapeInformer
	// VMRules returns a VMRuleInformer.
	VMRules() VMRuleInformer
	// VMServiceScrapes returns a VMServiceScrapeInformer.
	VMServiceScrapes() VMServiceScrapeInformer
	// VMSingles returns a VMSingleInformer.
	VMSingles() VMSingleInformer
	// VMStaticScrapes returns a VMStaticScrapeInformer.
	VMStaticScrapes() VMStaticScrapeInformer
	// VMUsers returns a VMUserInformer.
	VMUsers() VMUserInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// VMAgents returns a VMAgentInformer.
func (v *version) VMAgents() VMAgentInformer {
	return &vMAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMAlerts returns a VMAlertInformer.
func (v *version) VMAlerts() VMAlertInformer {
	return &vMAlertInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMAlertmanagers returns a VMAlertmanagerInformer.
func (v *version) VMAlertmanagers() VMAlertmanagerInformer {
	return &vMAlertmanagerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMAlertmanagerConfigs returns a VMAlertmanagerConfigInformer.
func (v *version) VMAlertmanagerConfigs() VMAlertmanagerConfigInformer {
	return &vMAlertmanagerConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMAuths returns a VMAuthInformer.
func (v *version) VMAuths() VMAuthInformer {
	return &vMAuthInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMClusters returns a VMClusterInformer.
func (v *version) VMClusters() VMClusterInformer {
	return &vMClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMNodeScrapes returns a VMNodeScrapeInformer.
func (v *version) VMNodeScrapes() VMNodeScrapeInformer {
	return &vMNodeScrapeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMPodScrapes returns a VMPodScrapeInformer.
func (v *version) VMPodScrapes() VMPodScrapeInformer {
	return &vMPodScrapeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMRules returns a VMRuleInformer.
func (v *version) VMRules() VMRuleInformer {
	return &vMRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMServiceScrapes returns a VMServiceScrapeInformer.
func (v *version) VMServiceScrapes() VMServiceScrapeInformer {
	return &vMServiceScrapeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMSingles returns a VMSingleInformer.
func (v *version) VMSingles() VMSingleInformer {
	return &vMSingleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMStaticScrapes returns a VMStaticScrapeInformer.
func (v *version) VMStaticScrapes() VMStaticScrapeInformer {
	return &vMStaticScrapeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMUsers returns a VMUserInformer.
func (v *version) VMUsers() VMUserInformer {
	return &vMUserInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
