kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vm-operator
subjects:
  - kind: ServiceAccount
    name: vm-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: vm-operator
  apiGroup: rbac.authorization.k8s.io