//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMClusterAgentPair) DeepCopyInto(out *VMClusterAgentPair) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
	if in.VMAgent != nil {
		in, out := &in.VMAgent, &out.VMAgent
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMClusterAgentPair.
func (in *VMClusterAgentPair) DeepCopy() *VMClusterAgentPair {
	if in == nil {
		return nil
	}
	out := new(VMClusterAgentPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMClusterStatus) DeepCopyInto(out *VMClusterStatus) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMClusterStatus.
func (in *VMClusterStatus) DeepCopy() *VMClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VMClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMDistributedCluster) DeepCopyInto(out *VMDistributedCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.ParsedLastAppliedSpec != nil {
		in, out := &in.ParsedLastAppliedSpec, &out.ParsedLastAppliedSpec
		*out = new(VMDistributedClusterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMDistributedCluster.
func (in *VMDistributedCluster) DeepCopy() *VMDistributedCluster {
	if in == nil {
		return nil
	}
	out := new(VMDistributedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMDistributedCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMDistributedClusterList) DeepCopyInto(out *VMDistributedClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMDistributedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMDistributedClusterList.
func (in *VMDistributedClusterList) DeepCopy() *VMDistributedClusterList {
	if in == nil {
		return nil
	}
	out := new(VMDistributedClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMDistributedClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMDistributedClusterSpec) DeepCopyInto(out *VMDistributedClusterSpec) {
	*out = *in
	out.VMUser = in.VMUser
	if in.VMClusters != nil {
		in, out := &in.VMClusters, &out.VMClusters
		*out = make([]VMClusterAgentPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMDistributedClusterSpec.
func (in *VMDistributedClusterSpec) DeepCopy() *VMDistributedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VMDistributedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMDistributedClusterStatus) DeepCopyInto(out *VMDistributedClusterStatus) {
	*out = *in
	in.StatusMetadata.DeepCopyInto(&out.StatusMetadata)
	if in.VMClusterInfo != nil {
		in, out := &in.VMClusterInfo, &out.VMClusterInfo
		*out = make([]VMClusterStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMDistributedClusterStatus.
func (in *VMDistributedClusterStatus) DeepCopy() *VMDistributedClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VMDistributedClusterStatus)
	in.DeepCopyInto(out)
	return out
}
