- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/single/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/hpa/properties
