- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestsLoadBalancer/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestsLoadBalancer/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/storage/properties/volumeClaimTemplate/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/storage/properties/volumeClaimTemplate/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/claimTemplates/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/claimTemplates/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/claimTemplates/items/properties/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/claimTemplates/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/volumes/items/properties
