- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmauth/properties/spec/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/claimTemplates/items/properties/metadata/x-kubernetes-preserve-unknown-fields
  value: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zoneCommon/properties/vmagent/properties/spec/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/claimTemplates/items/properties/metadata/x-kubernetes-preserve-unknown-fields
  value: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/zones/items/properties/vmagent/properties/spec/properties/volumes/items/properties
