- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestsLoadBalancer/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestsLoadBalancer/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/storage/properties/volumeClaimTemplate/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/storage/properties/volumeClaimTemplate/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/claimTemplates/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/claimTemplates/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storage/properties/serviceScrapeSpec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/select/properties/serviceScrapeSpec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/insert/properties/serviceScrapeSpec/properties
