- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestsLoadBalancer/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestsLoadBalancer/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/storage/properties/volumeClaimTemplate/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/storage/properties/volumeClaimTemplate/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/claimTemplates/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/claimTemplates/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlstorage/properties/serviceScrapeSpec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlselect/properties/serviceScrapeSpec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vlinsert/properties/serviceScrapeSpec/properties
