apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: vmsingle-sample
spec:
  # TODO(user): Add fields here
