apiVersion: operator.victoriametrics.com/v1
kind: VMAnomalyConfig
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample
spec:
  models:
    example:
      class: zscore
      z_threshold: 3.0
  schedulers:
    example:
      class: periodic
      infer_every: 2m
      fit_every: 4m
      fit_window: 5h
