apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: vmnodescrape-sample
spec:
  port: "9100"
  scheme: "http"
  jobLabel: "beta.kubernetes.io/os"
  targetLabels: ["beta.kubernetes.io/os"]
  path: "/metrics"
  selector:
    matchLabels:
      role: node-exporter
  interval: "10s"
  scrapeTimeout: "2s"
  tlsConfig:
    insecureSkipVerify: true
    caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  relabelConfigs:
    - sourceLabels: [ "node" ]
      targetLabel: "kubernetes_io_node1"
