apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: example-vmalert
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
  notifiers:
  - url: "http://vmalertmanager-example-alertmanager.default.svc:9093"
  evaluationInterval: "30s"
  ruleSelector: {}
  resources:
    requests:
      cpu: "150m"
      memory: "350Mi"
    limits:
      cpu: "350m"
      memory: "450Mi"
  remoteWrite:
    url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
    concurrency: 12
  remoteRead:
    url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429"
