/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.31. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// VMProbeLister helps list VMProbes.
// All objects returned here must be treated as read-only.
type VMProbeLister interface {
	// List lists all VMProbes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMProbe, err error)
	// VMProbes returns an object that can list and get VMProbes.
	VMProbes(namespace string) VMProbeNamespaceLister
	VMProbeListerExpansion
}

// vMProbeLister implements the VMProbeLister interface.
type vMProbeLister struct {
	listers.ResourceIndexer[*v1beta1.VMProbe]
}

// NewVMProbeLister returns a new VMProbeLister.
func NewVMProbeLister(indexer cache.Indexer) VMProbeLister {
	return &vMProbeLister{listers.New[*v1beta1.VMProbe](indexer, v1beta1.Resource("vmprobe"))}
}

// VMProbes returns an object that can list and get VMProbes.
func (s *vMProbeLister) VMProbes(namespace string) VMProbeNamespaceLister {
	return vMProbeNamespaceLister{listers.NewNamespaced[*v1beta1.VMProbe](s.ResourceIndexer, namespace)}
}

// VMProbeNamespaceLister helps list and get VMProbes.
// All objects returned here must be treated as read-only.
type VMProbeNamespaceLister interface {
	// List lists all VMProbes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMProbe, err error)
	// Get retrieves the VMProbe from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.VMProbe, error)
	VMProbeNamespaceListerExpansion
}

// vMProbeNamespaceLister implements the VMProbeNamespaceLister
// interface.
type vMProbeNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.VMProbe]
}
