/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.30. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VMRuleLister helps list VMRules.
// All objects returned here must be treated as read-only.
type VMRuleLister interface {
	// List lists all VMRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMRule, err error)
	// VMRules returns an object that can list and get VMRules.
	VMRules(namespace string) VMRuleNamespaceLister
	VMRuleListerExpansion
}

// vMRuleLister implements the VMRuleLister interface.
type vMRuleLister struct {
	indexer cache.Indexer
}

// NewVMRuleLister returns a new VMRuleLister.
func NewVMRuleLister(indexer cache.Indexer) VMRuleLister {
	return &vMRuleLister{indexer: indexer}
}

// List lists all VMRules in the indexer.
func (s *vMRuleLister) List(selector labels.Selector) (ret []*v1beta1.VMRule, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.VMRule))
	})
	return ret, err
}

// VMRules returns an object that can list and get VMRules.
func (s *vMRuleLister) VMRules(namespace string) VMRuleNamespaceLister {
	return vMRuleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VMRuleNamespaceLister helps list and get VMRules.
// All objects returned here must be treated as read-only.
type VMRuleNamespaceLister interface {
	// List lists all VMRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMRule, err error)
	// Get retrieves the VMRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.VMRule, error)
	VMRuleNamespaceListerExpansion
}

// vMRuleNamespaceLister implements the VMRuleNamespaceLister
// interface.
type vMRuleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VMRules in the indexer for a given namespace.
func (s vMRuleNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.VMRule, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.VMRule))
	})
	return ret, err
}

// Get retrieves the VMRule from the indexer for a given namespace and name.
func (s vMRuleNamespaceLister) Get(name string) (*v1beta1.VMRule, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("vmrule"), name)
	}
	return obj.(*v1beta1.VMRule), nil
}
