/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.31. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// VMScrapeConfigLister helps list VMScrapeConfigs.
// All objects returned here must be treated as read-only.
type VMScrapeConfigLister interface {
	// List lists all VMScrapeConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMScrapeConfig, err error)
	// VMScrapeConfigs returns an object that can list and get VMScrapeConfigs.
	VMScrapeConfigs(namespace string) VMScrapeConfigNamespaceLister
	VMScrapeConfigListerExpansion
}

// vMScrapeConfigLister implements the VMScrapeConfigLister interface.
type vMScrapeConfigLister struct {
	listers.ResourceIndexer[*v1beta1.VMScrapeConfig]
}

// NewVMScrapeConfigLister returns a new VMScrapeConfigLister.
func NewVMScrapeConfigLister(indexer cache.Indexer) VMScrapeConfigLister {
	return &vMScrapeConfigLister{listers.New[*v1beta1.VMScrapeConfig](indexer, v1beta1.Resource("vmscrapeconfig"))}
}

// VMScrapeConfigs returns an object that can list and get VMScrapeConfigs.
func (s *vMScrapeConfigLister) VMScrapeConfigs(namespace string) VMScrapeConfigNamespaceLister {
	return vMScrapeConfigNamespaceLister{listers.NewNamespaced[*v1beta1.VMScrapeConfig](s.ResourceIndexer, namespace)}
}

// VMScrapeConfigNamespaceLister helps list and get VMScrapeConfigs.
// All objects returned here must be treated as read-only.
type VMScrapeConfigNamespaceLister interface {
	// List lists all VMScrapeConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMScrapeConfig, err error)
	// Get retrieves the VMScrapeConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.VMScrapeConfig, error)
	VMScrapeConfigNamespaceListerExpansion
}

// vMScrapeConfigNamespaceLister implements the VMScrapeConfigNamespaceLister
// interface.
type vMScrapeConfigNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.VMScrapeConfig]
}
