/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.32. DO NOT EDIT.

package v1beta1

import (
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VMSingleLister helps list VMSingles.
// All objects returned here must be treated as read-only.
type VMSingleLister interface {
	// List lists all VMSingles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1beta1.VMSingle, err error)
	// VMSingles returns an object that can list and get VMSingles.
	VMSingles(namespace string) VMSingleNamespaceLister
	VMSingleListerExpansion
}

// vMSingleLister implements the VMSingleLister interface.
type vMSingleLister struct {
	listers.ResourceIndexer[*operatorv1beta1.VMSingle]
}

// NewVMSingleLister returns a new VMSingleLister.
func NewVMSingleLister(indexer cache.Indexer) VMSingleLister {
	return &vMSingleLister{listers.New[*operatorv1beta1.VMSingle](indexer, operatorv1beta1.Resource("vmsingle"))}
}

// VMSingles returns an object that can list and get VMSingles.
func (s *vMSingleLister) VMSingles(namespace string) VMSingleNamespaceLister {
	return vMSingleNamespaceLister{listers.NewNamespaced[*operatorv1beta1.VMSingle](s.ResourceIndexer, namespace)}
}

// VMSingleNamespaceLister helps list and get VMSingles.
// All objects returned here must be treated as read-only.
type VMSingleNamespaceLister interface {
	// List lists all VMSingles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1beta1.VMSingle, err error)
	// Get retrieves the VMSingle from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1beta1.VMSingle, error)
	VMSingleNamespaceListerExpansion
}

// vMSingleNamespaceLister implements the VMSingleNamespaceLister
// interface.
type vMSingleNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1beta1.VMSingle]
}
