/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.32. DO NOT EDIT.

package v1beta1

import (
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VMUserLister helps list VMUsers.
// All objects returned here must be treated as read-only.
type VMUserLister interface {
	// List lists all VMUsers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1beta1.VMUser, err error)
	// VMUsers returns an object that can list and get VMUsers.
	VMUsers(namespace string) VMUserNamespaceLister
	VMUserListerExpansion
}

// vMUserLister implements the VMUserLister interface.
type vMUserLister struct {
	listers.ResourceIndexer[*operatorv1beta1.VMUser]
}

// NewVMUserLister returns a new VMUserLister.
func NewVMUserLister(indexer cache.Indexer) VMUserLister {
	return &vMUserLister{listers.New[*operatorv1beta1.VMUser](indexer, operatorv1beta1.Resource("vmuser"))}
}

// VMUsers returns an object that can list and get VMUsers.
func (s *vMUserLister) VMUsers(namespace string) VMUserNamespaceLister {
	return vMUserNamespaceLister{listers.NewNamespaced[*operatorv1beta1.VMUser](s.ResourceIndexer, namespace)}
}

// VMUserNamespaceLister helps list and get VMUsers.
// All objects returned here must be treated as read-only.
type VMUserNamespaceLister interface {
	// List lists all VMUsers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1beta1.VMUser, err error)
	// Get retrieves the VMUser from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1beta1.VMUser, error)
	VMUserNamespaceListerExpansion
}

// vMUserNamespaceLister implements the VMUserNamespaceLister
// interface.
type vMUserNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1beta1.VMUser]
}
