/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.32. DO NOT EDIT.

package v1

import (
	operatorv1 "github.com/VictoriaMetrics/operator/api/operator/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VMStreamAggrRuleLister helps list VMStreamAggrRules.
// All objects returned here must be treated as read-only.
type VMStreamAggrRuleLister interface {
	// List lists all VMStreamAggrRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1.VMStreamAggrRule, err error)
	// VMStreamAggrRules returns an object that can list and get VMStreamAggrRules.
	VMStreamAggrRules(namespace string) VMStreamAggrRuleNamespaceLister
	VMStreamAggrRuleListerExpansion
}

// vMStreamAggrRuleLister implements the VMStreamAggrRuleLister interface.
type vMStreamAggrRuleLister struct {
	listers.ResourceIndexer[*operatorv1.VMStreamAggrRule]
}

// NewVMStreamAggrRuleLister returns a new VMStreamAggrRuleLister.
func NewVMStreamAggrRuleLister(indexer cache.Indexer) VMStreamAggrRuleLister {
	return &vMStreamAggrRuleLister{listers.New[*operatorv1.VMStreamAggrRule](indexer, operatorv1.Resource("vmstreamaggrrule"))}
}

// VMStreamAggrRules returns an object that can list and get VMStreamAggrRules.
func (s *vMStreamAggrRuleLister) VMStreamAggrRules(namespace string) VMStreamAggrRuleNamespaceLister {
	return vMStreamAggrRuleNamespaceLister{listers.NewNamespaced[*operatorv1.VMStreamAggrRule](s.ResourceIndexer, namespace)}
}

// VMStreamAggrRuleNamespaceLister helps list and get VMStreamAggrRules.
// All objects returned here must be treated as read-only.
type VMStreamAggrRuleNamespaceLister interface {
	// List lists all VMStreamAggrRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1.VMStreamAggrRule, err error)
	// Get retrieves the VMStreamAggrRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1.VMStreamAggrRule, error)
	VMStreamAggrRuleNamespaceListerExpansion
}

// vMStreamAggrRuleNamespaceLister implements the VMStreamAggrRuleNamespaceLister
// interface.
type vMStreamAggrRuleNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1.VMStreamAggrRule]
}
