/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.36. DO NOT EDIT.

package v1

import (
	operatorv1 "github.com/VictoriaMetrics/operator/api/operator/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VTAgentLister helps list VTAgents.
// All objects returned here must be treated as read-only.
type VTAgentLister interface {
	// List lists all VTAgents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1.VTAgent, err error)
	// VTAgents returns an object that can list and get VTAgents.
	VTAgents(namespace string) VTAgentNamespaceLister
	VTAgentListerExpansion
}

// vTAgentLister implements the VTAgentLister interface.
type vTAgentLister struct {
	listers.ResourceIndexer[*operatorv1.VTAgent]
}

// NewVTAgentLister returns a new VTAgentLister.
func NewVTAgentLister(indexer cache.Indexer) VTAgentLister {
	return &vTAgentLister{listers.New[*operatorv1.VTAgent](indexer, operatorv1.Resource("vtagent"))}
}

// VTAgents returns an object that can list and get VTAgents.
func (s *vTAgentLister) VTAgents(namespace string) VTAgentNamespaceLister {
	return vTAgentNamespaceLister{listers.NewNamespaced[*operatorv1.VTAgent](s.ResourceIndexer, namespace)}
}

// VTAgentNamespaceLister helps list and get VTAgents.
// All objects returned here must be treated as read-only.
type VTAgentNamespaceLister interface {
	// List lists all VTAgents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1.VTAgent, err error)
	// Get retrieves the VTAgent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1.VTAgent, error)
	VTAgentNamespaceListerExpansion
}

// vTAgentNamespaceLister implements the VTAgentNamespaceLister
// interface.
type vTAgentNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1.VTAgent]
}
