/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen-v0.32. DO NOT EDIT.

package v1

import (
	operatorv1 "github.com/VictoriaMetrics/operator/api/operator/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VTClusterLister helps list VTClusters.
// All objects returned here must be treated as read-only.
type VTClusterLister interface {
	// List lists all VTClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1.VTCluster, err error)
	// VTClusters returns an object that can list and get VTClusters.
	VTClusters(namespace string) VTClusterNamespaceLister
	VTClusterListerExpansion
}

// vTClusterLister implements the VTClusterLister interface.
type vTClusterLister struct {
	listers.ResourceIndexer[*operatorv1.VTCluster]
}

// NewVTClusterLister returns a new VTClusterLister.
func NewVTClusterLister(indexer cache.Indexer) VTClusterLister {
	return &vTClusterLister{listers.New[*operatorv1.VTCluster](indexer, operatorv1.Resource("vtcluster"))}
}

// VTClusters returns an object that can list and get VTClusters.
func (s *vTClusterLister) VTClusters(namespace string) VTClusterNamespaceLister {
	return vTClusterNamespaceLister{listers.NewNamespaced[*operatorv1.VTCluster](s.ResourceIndexer, namespace)}
}

// VTClusterNamespaceLister helps list and get VTClusters.
// All objects returned here must be treated as read-only.
type VTClusterNamespaceLister interface {
	// List lists all VTClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1.VTCluster, err error)
	// Get retrieves the VTCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1.VTCluster, error)
	VTClusterNamespaceListerExpansion
}

// vTClusterNamespaceLister implements the VTClusterNamespaceLister
// interface.
type vTClusterNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1.VTCluster]
}
