//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLSingle) DeepCopyInto(out *VLSingle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.ParsedLastAppliedSpec != nil {
		in, out := &in.ParsedLastAppliedSpec, &out.ParsedLastAppliedSpec
		*out = new(VLSingleSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLSingle.
func (in *VLSingle) DeepCopy() *VLSingle {
	if in == nil {
		return nil
	}
	out := new(VLSingle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLSingle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLSingleList) DeepCopyInto(out *VLSingleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLSingle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLSingleList.
func (in *VLSingleList) DeepCopy() *VLSingleList {
	if in == nil {
		return nil
	}
	out := new(VLSingleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLSingleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLSingleSpec) DeepCopyInto(out *VLSingleSpec) {
	*out = *in
	if in.PodMetadata != nil {
		in, out := &in.PodMetadata, &out.PodMetadata
		*out = new(v1beta1.EmbeddedObjectMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagedMetadata != nil {
		in, out := &in.ManagedMetadata, &out.ManagedMetadata
		*out = new(v1beta1.ManagedObjectsMetadata)
		(*in).DeepCopyInto(*out)
	}
	in.CommonDefaultableParams.DeepCopyInto(&out.CommonDefaultableParams)
	in.CommonApplicationDeploymentParams.DeepCopyInto(&out.CommonApplicationDeploymentParams)
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(corev1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
	in.StorageMetadata.DeepCopyInto(&out.StorageMetadata)
	if in.ServiceSpec != nil {
		in, out := &in.ServiceSpec, &out.ServiceSpec
		*out = new(v1beta1.AdditionalServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceScrapeSpec != nil {
		in, out := &in.ServiceScrapeSpec, &out.ServiceScrapeSpec
		*out = new(v1beta1.VMServiceScrapeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EmbeddedProbes != nil {
		in, out := &in.EmbeddedProbes, &out.EmbeddedProbes
		*out = new(v1beta1.EmbeddedProbes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLSingleSpec.
func (in *VLSingleSpec) DeepCopy() *VLSingleSpec {
	if in == nil {
		return nil
	}
	out := new(VLSingleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLSingleStatus) DeepCopyInto(out *VLSingleStatus) {
	*out = *in
	in.StatusMetadata.DeepCopyInto(&out.StatusMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLSingleStatus.
func (in *VLSingleStatus) DeepCopy() *VLSingleStatus {
	if in == nil {
		return nil
	}
	out := new(VLSingleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMAnomaly) DeepCopyInto(out *VMAnomaly) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.ParsedLastAppliedSpec != nil {
		in, out := &in.ParsedLastAppliedSpec, &out.ParsedLastAppliedSpec
		*out = new(VMAnomalySpec)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMAnomaly.
func (in *VMAnomaly) DeepCopy() *VMAnomaly {
	if in == nil {
		return nil
	}
	out := new(VMAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMAnomaly) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMAnomalyList) DeepCopyInto(out *VMAnomalyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMAnomalyList.
func (in *VMAnomalyList) DeepCopy() *VMAnomalyList {
	if in == nil {
		return nil
	}
	out := new(VMAnomalyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMAnomalyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMAnomalySpec) DeepCopyInto(out *VMAnomalySpec) {
	*out = *in
	if in.PodMetadata != nil {
		in, out := &in.PodMetadata, &out.PodMetadata
		*out = new(v1beta1.EmbeddedObjectMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagedMetadata != nil {
		in, out := &in.ManagedMetadata, &out.ManagedMetadata
		*out = new(v1beta1.ManagedObjectsMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceScrapeSpec != nil {
		in, out := &in.ServiceScrapeSpec, &out.ServiceScrapeSpec
		*out = new(v1beta1.VMServiceScrapeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardCount != nil {
		in, out := &in.ShardCount, &out.ShardCount
		*out = new(int)
		**out = **in
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(appsv1.DeploymentStrategyType)
		**out = **in
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(appsv1.RollingUpdateDeployment)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(v1beta1.EmbeddedPodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EmbeddedProbes != nil {
		in, out := &in.EmbeddedProbes, &out.EmbeddedProbes
		*out = new(v1beta1.EmbeddedProbes)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulStorage != nil {
		in, out := &in.StatefulStorage, &out.StatefulStorage
		*out = new(v1beta1.StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClaimTemplates != nil {
		in, out := &in.ClaimTemplates, &out.ClaimTemplates
		*out = make([]corev1.PersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(v1beta1.License)
		(*in).DeepCopyInto(*out)
	}
	in.CommonDefaultableParams.DeepCopyInto(&out.CommonDefaultableParams)
	in.CommonConfigReloaderParams.DeepCopyInto(&out.CommonConfigReloaderParams)
	in.CommonApplicationDeploymentParams.DeepCopyInto(&out.CommonApplicationDeploymentParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMAnomalySpec.
func (in *VMAnomalySpec) DeepCopy() *VMAnomalySpec {
	if in == nil {
		return nil
	}
	out := new(VMAnomalySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMAnomalyStatus) DeepCopyInto(out *VMAnomalyStatus) {
	*out = *in
	in.StatusMetadata.DeepCopyInto(&out.StatusMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMAnomalyStatus.
func (in *VMAnomalyStatus) DeepCopy() *VMAnomalyStatus {
	if in == nil {
		return nil
	}
	out := new(VMAnomalyStatus)
	in.DeepCopyInto(out)
	return out
}
