apiVersion: operator.victoriametrics.com/v1
kind: VLAgent
metadata:
  name: example
spec:
  replicaCount: 2
  resources:
    requests:
      cpu: "50m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
  remoteWrite:
    - url: "http://vlsingle-example-0.default.svc:9428/internal/insert"
      maxDiskUsage: 10GB
  remoteWriteSettings:
    # ~ 5GB in bytes
    maxBlockSize: 30MB
