apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: vlsingle-zone-b
spec:
  retentionPeriod: "14d"
---
apiVersion: operator.victoriametrics.com/v1alpha1
kind: VLDistributed
metadata:
  name: sample-with-vlsingle
spec:
  backendType: VLSingle
  vmauth:
    spec:
      unauthorizedUserAccessSpec:
        targetRefs:
          - name: read
          - name: write
      replicaCount: 1
  zoneCommon:
    vlagent:
      spec:
        replicaCount: 1
    vlsingle:
      spec:
        retentionPeriod: "30d"
  zones:
    - name: zone-a
    - name: zone-b
      # Reference an explicitly pre-created VLSingle object
      vlsingle:
        name: vlsingle-zone-b
        spec:
          retentionPeriod: "14d"
