apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: per-node
spec:
  selectAllByDefault: true
  resources:
    requests:
      cpu: "50m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  daemonSetMode: true
  useVMConfigReloader: true
  remoteWrite:
    - url: "http://vmsingle-dc-1.default.svc:8429/api/v1/write"
      maxDiskUsage: 5GB
  remoteWriteSettings:
    tmpDataPath: "/opt/queue"
  volumes:
    - name: persistent-queue
      hostPath:
        path: /opt/mnt/vmagent-queue
  volumeMounts:
    - mountPath: /opt/queue
      name: persistent-queue
