apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: example-email-web
spec:
  route:
    receiver: email
    group_interval: 1m
    routes:
    - receiver: email
  receivers:
    - name: email
      email_configs:
        - to: some-email@example.com
          from: alerting@example.com
          smarthost: example.com:25
          text: ALARM
      webhook_configs:
        - url: http://some-other-wh
