apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth-sample
spec:
  userSelector:
    matchLabels:
      managed-by: vm-operator
    matchExpressions:
    - operator: Exists
      key: name
  userNamespaceSelector:
    matchLabels:
      managed-by: vm-operator
    matchExpressions:
    - operator: Exists
      key: name
  image:
    repository: victoriametrics/vmauth
    tag: v1.60.0
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: "250m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
