apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-persistent
spec:
  retentionPeriod: "4"
  replicationFactor: 2
  vmstorage:
    replicaCount: 2
    containers:
    - name: my-custom-backup-image
      volumeMounts:
      - name: vmbackup-dir
        mountPath: /opt/backups
    claimTemplates:
    - matedata:
        name: vmbackup-dir
      spec:
        resources:
          requests:
            storage: 50Gi
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
    resources:
      limits:
        cpu: "1"
        memory: 1500Mi
  vmselect:
    replicaCount: 2
    claimTemplates: []
    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
    resources:
      limits:
        cpu: "1"
        memory: "1000Mi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
  vminsert:
    replicaCount: 2
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: "0.5"
        memory: "500Mi"
