apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: sample-new
spec:
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zoneCommon:
    vmcluster:
      spec:
        retentionPeriod: "4"
        replicationFactor: 2
        vmstorage:
          replicaCount: 2
          storageDataPath: "/vm-data"
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 10Gi
        vmselect:
          replicaCount: 2
          cacheMountPath: "/select-cache"
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 2Gi
        vminsert:
          replicaCount: 2
  zones:
    - name: us-east-1
    - name: us-west-2
    - name: eu-west-1
