apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: sample-override
spec:
  vmauth:
    name: global-vmauth
    spec:
      replicaCount: 1
      unauthorizedUserAccessSpec:
        targetRefs:
          - name: read
          - name: write
  zoneCommon:
    vmagent:
      spec:
        replicaCount: 1
    vmcluster:
      name: vmcluster-%ZONE%
      spec:
        vmstorage:
          replicaCount: 1
        vmselect:
          replicaCount: 1
        vminsert:
          replicaCount: 1
  zones:
    - name: us-east-1
    - name: us-west-2
