/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen-v0.31. DO NOT EDIT.

package v1beta1

import (
	"context"

	scheme "github.com/VictoriaMetrics/operator/api/client/versioned/scheme"
	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VMRulesGetter has a method to return a VMRuleInterface.
// A group's client should implement this interface.
type VMRulesGetter interface {
	VMRules(namespace string) VMRuleInterface
}

// VMRuleInterface has methods to work with VMRule resources.
type VMRuleInterface interface {
	Create(ctx context.Context, vMRule *v1beta1.VMRule, opts v1.CreateOptions) (*v1beta1.VMRule, error)
	Update(ctx context.Context, vMRule *v1beta1.VMRule, opts v1.UpdateOptions) (*v1beta1.VMRule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vMRule *v1beta1.VMRule, opts v1.UpdateOptions) (*v1beta1.VMRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VMRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VMRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMRule, err error)
	VMRuleExpansion
}

// vMRules implements VMRuleInterface
type vMRules struct {
	*gentype.ClientWithList[*v1beta1.VMRule, *v1beta1.VMRuleList]
}

// newVMRules returns a VMRules
func newVMRules(c *OperatorV1beta1Client, namespace string) *vMRules {
	return &vMRules{
		gentype.NewClientWithList[*v1beta1.VMRule, *v1beta1.VMRuleList](
			"vmrules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.VMRule { return &v1beta1.VMRule{} },
			func() *v1beta1.VMRuleList { return &v1beta1.VMRuleList{} }),
	}
}
