/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen-v0.30. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/VictoriaMetrics/operator/api/client/versioned/scheme"
	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VMScrapeConfigsGetter has a method to return a VMScrapeConfigInterface.
// A group's client should implement this interface.
type VMScrapeConfigsGetter interface {
	VMScrapeConfigs(namespace string) VMScrapeConfigInterface
}

// VMScrapeConfigInterface has methods to work with VMScrapeConfig resources.
type VMScrapeConfigInterface interface {
	Create(ctx context.Context, vMScrapeConfig *v1beta1.VMScrapeConfig, opts v1.CreateOptions) (*v1beta1.VMScrapeConfig, error)
	Update(ctx context.Context, vMScrapeConfig *v1beta1.VMScrapeConfig, opts v1.UpdateOptions) (*v1beta1.VMScrapeConfig, error)
	UpdateStatus(ctx context.Context, vMScrapeConfig *v1beta1.VMScrapeConfig, opts v1.UpdateOptions) (*v1beta1.VMScrapeConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VMScrapeConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VMScrapeConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMScrapeConfig, err error)
	VMScrapeConfigExpansion
}

// vMScrapeConfigs implements VMScrapeConfigInterface
type vMScrapeConfigs struct {
	client rest.Interface
	ns     string
}

// newVMScrapeConfigs returns a VMScrapeConfigs
func newVMScrapeConfigs(c *OperatorV1beta1Client, namespace string) *vMScrapeConfigs {
	return &vMScrapeConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vMScrapeConfig, and returns the corresponding vMScrapeConfig object, and an error if there is any.
func (c *vMScrapeConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VMScrapeConfig, err error) {
	result = &v1beta1.VMScrapeConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VMScrapeConfigs that match those selectors.
func (c *vMScrapeConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VMScrapeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VMScrapeConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vMScrapeConfigs.
func (c *vMScrapeConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vMScrapeConfig and creates it.  Returns the server's representation of the vMScrapeConfig, and an error, if there is any.
func (c *vMScrapeConfigs) Create(ctx context.Context, vMScrapeConfig *v1beta1.VMScrapeConfig, opts v1.CreateOptions) (result *v1beta1.VMScrapeConfig, err error) {
	result = &v1beta1.VMScrapeConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMScrapeConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vMScrapeConfig and updates it. Returns the server's representation of the vMScrapeConfig, and an error, if there is any.
func (c *vMScrapeConfigs) Update(ctx context.Context, vMScrapeConfig *v1beta1.VMScrapeConfig, opts v1.UpdateOptions) (result *v1beta1.VMScrapeConfig, err error) {
	result = &v1beta1.VMScrapeConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		Name(vMScrapeConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMScrapeConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vMScrapeConfigs) UpdateStatus(ctx context.Context, vMScrapeConfig *v1beta1.VMScrapeConfig, opts v1.UpdateOptions) (result *v1beta1.VMScrapeConfig, err error) {
	result = &v1beta1.VMScrapeConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		Name(vMScrapeConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMScrapeConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vMScrapeConfig and deletes it. Returns an error if one occurs.
func (c *vMScrapeConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vMScrapeConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vMScrapeConfig.
func (c *vMScrapeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMScrapeConfig, err error) {
	result = &v1beta1.VMScrapeConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vmscrapeconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
