/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/VictoriaMetrics/operator/api/client/versioned/scheme"
	v1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VMUsersGetter has a method to return a VMUserInterface.
// A group's client should implement this interface.
type VMUsersGetter interface {
	VMUsers(namespace string) VMUserInterface
}

// VMUserInterface has methods to work with VMUser resources.
type VMUserInterface interface {
	Create(ctx context.Context, vMUser *v1beta1.VMUser, opts v1.CreateOptions) (*v1beta1.VMUser, error)
	Update(ctx context.Context, vMUser *v1beta1.VMUser, opts v1.UpdateOptions) (*v1beta1.VMUser, error)
	UpdateStatus(ctx context.Context, vMUser *v1beta1.VMUser, opts v1.UpdateOptions) (*v1beta1.VMUser, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VMUser, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VMUserList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMUser, err error)
	VMUserExpansion
}

// vMUsers implements VMUserInterface
type vMUsers struct {
	client rest.Interface
	ns     string
}

// newVMUsers returns a VMUsers
func newVMUsers(c *OperatorV1beta1Client, namespace string) *vMUsers {
	return &vMUsers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vMUser, and returns the corresponding vMUser object, and an error if there is any.
func (c *vMUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VMUser, err error) {
	result = &v1beta1.VMUser{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmusers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VMUsers that match those selectors.
func (c *vMUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VMUserList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VMUserList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vMUsers.
func (c *vMUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vmusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vMUser and creates it.  Returns the server's representation of the vMUser, and an error, if there is any.
func (c *vMUsers) Create(ctx context.Context, vMUser *v1beta1.VMUser, opts v1.CreateOptions) (result *v1beta1.VMUser, err error) {
	result = &v1beta1.VMUser{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vmusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMUser).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vMUser and updates it. Returns the server's representation of the vMUser, and an error, if there is any.
func (c *vMUsers) Update(ctx context.Context, vMUser *v1beta1.VMUser, opts v1.UpdateOptions) (result *v1beta1.VMUser, err error) {
	result = &v1beta1.VMUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmusers").
		Name(vMUser.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMUser).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vMUsers) UpdateStatus(ctx context.Context, vMUser *v1beta1.VMUser, opts v1.UpdateOptions) (result *v1beta1.VMUser, err error) {
	result = &v1beta1.VMUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmusers").
		Name(vMUser.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMUser).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vMUser and deletes it. Returns an error if one occurs.
func (c *vMUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmusers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vMUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmusers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vMUser.
func (c *vMUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VMUser, err error) {
	result = &v1beta1.VMUser{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vmusers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
