/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/VictoriaMetrics/operator/api/victoriametrics/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VMAlertLister helps list VMAlerts.
// All objects returned here must be treated as read-only.
type VMAlertLister interface {
	// List lists all VMAlerts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMAlert, err error)
	// VMAlerts returns an object that can list and get VMAlerts.
	VMAlerts(namespace string) VMAlertNamespaceLister
	VMAlertListerExpansion
}

// vMAlertLister implements the VMAlertLister interface.
type vMAlertLister struct {
	indexer cache.Indexer
}

// NewVMAlertLister returns a new VMAlertLister.
func NewVMAlertLister(indexer cache.Indexer) VMAlertLister {
	return &vMAlertLister{indexer: indexer}
}

// List lists all VMAlerts in the indexer.
func (s *vMAlertLister) List(selector labels.Selector) (ret []*v1beta1.VMAlert, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.VMAlert))
	})
	return ret, err
}

// VMAlerts returns an object that can list and get VMAlerts.
func (s *vMAlertLister) VMAlerts(namespace string) VMAlertNamespaceLister {
	return vMAlertNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VMAlertNamespaceLister helps list and get VMAlerts.
// All objects returned here must be treated as read-only.
type VMAlertNamespaceLister interface {
	// List lists all VMAlerts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.VMAlert, err error)
	// Get retrieves the VMAlert from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.VMAlert, error)
	VMAlertNamespaceListerExpansion
}

// vMAlertNamespaceLister implements the VMAlertNamespaceLister
// interface.
type vMAlertNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VMAlerts in the indexer for a given namespace.
func (s vMAlertNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.VMAlert, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.VMAlert))
	})
	return ret, err
}

// Get retrieves the VMAlert from the indexer for a given namespace and name.
func (s vMAlertNamespaceLister) Get(name string) (*v1beta1.VMAlert, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("vmalert"), name)
	}
	return obj.(*v1beta1.VMAlert), nil
}
