/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1beta1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMAlertmanagerConfigInformer provides access to a shared informer and lister for
// VMAlertmanagerConfigs. Prefer using the type-safe variant (see [TypedVMAlertmanagerConfigInformer]).
type VMAlertmanagerConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1beta1.VMAlertmanagerConfigLister
}

// TypedVMAlertmanagerConfigInformer provides access to a shared informer and lister for
// VMAlertmanagerConfigs, including the type-safe TypedInformer variant.
// It is a superset of VMAlertmanagerConfigInformer.
type TypedVMAlertmanagerConfigInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VMAlertmanagerConfigIndexInformer
	Lister() operatorv1beta1.VMAlertmanagerConfigLister
}

// VMAlertmanagerConfigIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VMAlertmanagerConfigIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1beta1.VMAlertmanagerConfig]

// VMAlertmanagerConfigHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VMAlertmanagerConfig.
type VMAlertmanagerConfigHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1beta1.VMAlertmanagerConfig]

// VMAlertmanagerConfigDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VMAlertmanagerConfig.
type VMAlertmanagerConfigDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1beta1.VMAlertmanagerConfig]

// VMAlertmanagerConfigFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VMAlertmanagerConfig.
type VMAlertmanagerConfigFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1beta1.VMAlertmanagerConfig]

// VMAlertmanagerConfigIndexers is a specialization of [cache.TypedIndexers] for VMAlertmanagerConfig.
type VMAlertmanagerConfigIndexers = cache.TypedIndexers[*apioperatorv1beta1.VMAlertmanagerConfig]

// DeletedVMAlertmanagerConfig is a specialization of [cache.DeletedObject] for VMAlertmanagerConfig.
type DeletedVMAlertmanagerConfig = cache.DeletedObject[*apioperatorv1beta1.VMAlertmanagerConfig]

type vMAlertmanagerConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMAlertmanagerConfigInformer constructs a new informer for VMAlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMAlertmanagerConfigInformer]).
func NewVMAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVMAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVMAlertmanagerConfigInformer constructs a new informer for VMAlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMAlertmanagerConfigIndexers) VMAlertmanagerConfigIndexInformer {
	return NewTypedVMAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVMAlertmanagerConfigInformer constructs a new informer for VMAlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVMAlertmanagerConfigInformer]).
func NewFilteredVMAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVMAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVMAlertmanagerConfigInformer constructs a new informer for VMAlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVMAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMAlertmanagerConfigIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VMAlertmanagerConfigIndexInformer {
	return NewTypedVMAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVMAlertmanagerConfigInformerWithOptions constructs a new informer for VMAlertmanagerConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMAlertmanagerConfigInformerWithOptions]).
func NewVMAlertmanagerConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVMAlertmanagerConfigInformerWithOptions(client, namespace, options)
}

// NewTypedVMAlertmanagerConfigInformerWithOptions constructs a new informer for VMAlertmanagerConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMAlertmanagerConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VMAlertmanagerConfigIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1beta1", Resource: "vmalertmanagerconfigs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAlertmanagerConfig](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAlertmanagerConfigs(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAlertmanagerConfigs(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAlertmanagerConfigs(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAlertmanagerConfigs(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1beta1.VMAlertmanagerConfig{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vMAlertmanagerConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVMAlertmanagerConfigInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vMAlertmanagerConfigInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vMAlertmanagerConfigInformer) TypedInformer() VMAlertmanagerConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAlertmanagerConfig](f.factory.InformerFor(&apioperatorv1beta1.VMAlertmanagerConfig{}, f.defaultInformer))
}

func (f *vMAlertmanagerConfigInformer) Lister() operatorv1beta1.VMAlertmanagerConfigLister {
	return operatorv1beta1.NewVMAlertmanagerConfigLister(f.Informer().GetIndexer())
}

// ToTypedVMAlertmanagerConfigInformer converts an untyped informer into a TypedVMAlertmanagerConfigInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMAlertmanagerConfig. If that is not the case, calling type-safe methods of the returned
// TypedVMAlertmanagerConfigInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVMAlertmanagerConfigInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVMAlertmanagerConfigInformer(informer VMAlertmanagerConfigInformer) TypedVMAlertmanagerConfigInformer {
	if informer, ok := informer.(TypedVMAlertmanagerConfigInformer); ok {
		return informer
	}
	return &vMAlertmanagerConfigTypedInformerAdapter{informer}
}

type vMAlertmanagerConfigTypedInformerAdapter struct {
	VMAlertmanagerConfigInformer
}

func (a *vMAlertmanagerConfigTypedInformerAdapter) TypedInformer() VMAlertmanagerConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAlertmanagerConfig](a.Informer())
}

// ToVMAlertmanagerConfigIndexInformer converts an untyped informer into a VMAlertmanagerConfigIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMAlertmanagerConfig. If that is not the case, calling type-safe methods of the returned
// VMAlertmanagerConfigIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VMAlertmanagerConfigIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVMAlertmanagerConfigIndexInformer(informer cache.SharedIndexInformer) VMAlertmanagerConfigIndexInformer {
	if informer, ok := informer.(VMAlertmanagerConfigIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAlertmanagerConfig](informer)
}
