/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1beta1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMAuthInformer provides access to a shared informer and lister for
// VMAuths. Prefer using the type-safe variant (see [TypedVMAuthInformer]).
type VMAuthInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1beta1.VMAuthLister
}

// TypedVMAuthInformer provides access to a shared informer and lister for
// VMAuths, including the type-safe TypedInformer variant.
// It is a superset of VMAuthInformer.
type TypedVMAuthInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VMAuthIndexInformer
	Lister() operatorv1beta1.VMAuthLister
}

// VMAuthIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VMAuthIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1beta1.VMAuth]

// VMAuthHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VMAuth.
type VMAuthHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1beta1.VMAuth]

// VMAuthDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VMAuth.
type VMAuthDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1beta1.VMAuth]

// VMAuthFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VMAuth.
type VMAuthFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1beta1.VMAuth]

// VMAuthIndexers is a specialization of [cache.TypedIndexers] for VMAuth.
type VMAuthIndexers = cache.TypedIndexers[*apioperatorv1beta1.VMAuth]

// DeletedVMAuth is a specialization of [cache.DeletedObject] for VMAuth.
type DeletedVMAuth = cache.DeletedObject[*apioperatorv1beta1.VMAuth]

type vMAuthInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMAuthInformer constructs a new informer for VMAuth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMAuthInformer]).
func NewVMAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVMAuthInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVMAuthInformer constructs a new informer for VMAuth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMAuthIndexers) VMAuthIndexInformer {
	return NewTypedVMAuthInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVMAuthInformer constructs a new informer for VMAuth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVMAuthInformer]).
func NewFilteredVMAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVMAuthInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVMAuthInformer constructs a new informer for VMAuth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVMAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMAuthIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VMAuthIndexInformer {
	return NewTypedVMAuthInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVMAuthInformerWithOptions constructs a new informer for VMAuth type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMAuthInformerWithOptions]).
func NewVMAuthInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVMAuthInformerWithOptions(client, namespace, options)
}

// NewTypedVMAuthInformerWithOptions constructs a new informer for VMAuth type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMAuthInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VMAuthIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1beta1", Resource: "vmauths"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAuth](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAuths(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAuths(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAuths(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMAuths(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1beta1.VMAuth{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vMAuthInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVMAuthInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vMAuthInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vMAuthInformer) TypedInformer() VMAuthIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAuth](f.factory.InformerFor(&apioperatorv1beta1.VMAuth{}, f.defaultInformer))
}

func (f *vMAuthInformer) Lister() operatorv1beta1.VMAuthLister {
	return operatorv1beta1.NewVMAuthLister(f.Informer().GetIndexer())
}

// ToTypedVMAuthInformer converts an untyped informer into a TypedVMAuthInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMAuth. If that is not the case, calling type-safe methods of the returned
// TypedVMAuthInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVMAuthInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVMAuthInformer(informer VMAuthInformer) TypedVMAuthInformer {
	if informer, ok := informer.(TypedVMAuthInformer); ok {
		return informer
	}
	return &vMAuthTypedInformerAdapter{informer}
}

type vMAuthTypedInformerAdapter struct {
	VMAuthInformer
}

func (a *vMAuthTypedInformerAdapter) TypedInformer() VMAuthIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAuth](a.Informer())
}

// ToVMAuthIndexInformer converts an untyped informer into a VMAuthIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMAuth. If that is not the case, calling type-safe methods of the returned
// VMAuthIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VMAuthIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVMAuthIndexInformer(informer cache.SharedIndexInformer) VMAuthIndexInformer {
	if informer, ok := informer.(VMAuthIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMAuth](informer)
}
