/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1beta1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMClusterInformer provides access to a shared informer and lister for
// VMClusters. Prefer using the type-safe variant (see [TypedVMClusterInformer]).
type VMClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1beta1.VMClusterLister
}

// TypedVMClusterInformer provides access to a shared informer and lister for
// VMClusters, including the type-safe TypedInformer variant.
// It is a superset of VMClusterInformer.
type TypedVMClusterInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VMClusterIndexInformer
	Lister() operatorv1beta1.VMClusterLister
}

// VMClusterIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VMClusterIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1beta1.VMCluster]

// VMClusterHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VMCluster.
type VMClusterHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1beta1.VMCluster]

// VMClusterDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VMCluster.
type VMClusterDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1beta1.VMCluster]

// VMClusterFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VMCluster.
type VMClusterFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1beta1.VMCluster]

// VMClusterIndexers is a specialization of [cache.TypedIndexers] for VMCluster.
type VMClusterIndexers = cache.TypedIndexers[*apioperatorv1beta1.VMCluster]

// DeletedVMCluster is a specialization of [cache.DeletedObject] for VMCluster.
type DeletedVMCluster = cache.DeletedObject[*apioperatorv1beta1.VMCluster]

type vMClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMClusterInformer constructs a new informer for VMCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMClusterInformer]).
func NewVMClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVMClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVMClusterInformer constructs a new informer for VMCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMClusterIndexers) VMClusterIndexInformer {
	return NewTypedVMClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVMClusterInformer constructs a new informer for VMCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVMClusterInformer]).
func NewFilteredVMClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVMClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVMClusterInformer constructs a new informer for VMCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVMClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMClusterIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VMClusterIndexInformer {
	return NewTypedVMClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVMClusterInformerWithOptions constructs a new informer for VMCluster type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMClusterInformerWithOptions]).
func NewVMClusterInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVMClusterInformerWithOptions(client, namespace, options)
}

// NewTypedVMClusterInformerWithOptions constructs a new informer for VMCluster type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMClusterInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VMClusterIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1beta1", Resource: "vmclusters"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMCluster](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMClusters(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMClusters(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMClusters(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMClusters(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1beta1.VMCluster{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vMClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVMClusterInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vMClusterInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vMClusterInformer) TypedInformer() VMClusterIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMCluster](f.factory.InformerFor(&apioperatorv1beta1.VMCluster{}, f.defaultInformer))
}

func (f *vMClusterInformer) Lister() operatorv1beta1.VMClusterLister {
	return operatorv1beta1.NewVMClusterLister(f.Informer().GetIndexer())
}

// ToTypedVMClusterInformer converts an untyped informer into a TypedVMClusterInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMCluster. If that is not the case, calling type-safe methods of the returned
// TypedVMClusterInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVMClusterInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVMClusterInformer(informer VMClusterInformer) TypedVMClusterInformer {
	if informer, ok := informer.(TypedVMClusterInformer); ok {
		return informer
	}
	return &vMClusterTypedInformerAdapter{informer}
}

type vMClusterTypedInformerAdapter struct {
	VMClusterInformer
}

func (a *vMClusterTypedInformerAdapter) TypedInformer() VMClusterIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMCluster](a.Informer())
}

// ToVMClusterIndexInformer converts an untyped informer into a VMClusterIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMCluster. If that is not the case, calling type-safe methods of the returned
// VMClusterIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VMClusterIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVMClusterIndexInformer(informer cache.SharedIndexInformer) VMClusterIndexInformer {
	if informer, ok := informer.(VMClusterIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMCluster](informer)
}
