/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1beta1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMNodeScrapeInformer provides access to a shared informer and lister for
// VMNodeScrapes. Prefer using the type-safe variant (see [TypedVMNodeScrapeInformer]).
type VMNodeScrapeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1beta1.VMNodeScrapeLister
}

// TypedVMNodeScrapeInformer provides access to a shared informer and lister for
// VMNodeScrapes, including the type-safe TypedInformer variant.
// It is a superset of VMNodeScrapeInformer.
type TypedVMNodeScrapeInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VMNodeScrapeIndexInformer
	Lister() operatorv1beta1.VMNodeScrapeLister
}

// VMNodeScrapeIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VMNodeScrapeIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1beta1.VMNodeScrape]

// VMNodeScrapeHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VMNodeScrape.
type VMNodeScrapeHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1beta1.VMNodeScrape]

// VMNodeScrapeDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VMNodeScrape.
type VMNodeScrapeDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1beta1.VMNodeScrape]

// VMNodeScrapeFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VMNodeScrape.
type VMNodeScrapeFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1beta1.VMNodeScrape]

// VMNodeScrapeIndexers is a specialization of [cache.TypedIndexers] for VMNodeScrape.
type VMNodeScrapeIndexers = cache.TypedIndexers[*apioperatorv1beta1.VMNodeScrape]

// DeletedVMNodeScrape is a specialization of [cache.DeletedObject] for VMNodeScrape.
type DeletedVMNodeScrape = cache.DeletedObject[*apioperatorv1beta1.VMNodeScrape]

type vMNodeScrapeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMNodeScrapeInformer constructs a new informer for VMNodeScrape type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMNodeScrapeInformer]).
func NewVMNodeScrapeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVMNodeScrapeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVMNodeScrapeInformer constructs a new informer for VMNodeScrape type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMNodeScrapeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMNodeScrapeIndexers) VMNodeScrapeIndexInformer {
	return NewTypedVMNodeScrapeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVMNodeScrapeInformer constructs a new informer for VMNodeScrape type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVMNodeScrapeInformer]).
func NewFilteredVMNodeScrapeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVMNodeScrapeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVMNodeScrapeInformer constructs a new informer for VMNodeScrape type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVMNodeScrapeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMNodeScrapeIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VMNodeScrapeIndexInformer {
	return NewTypedVMNodeScrapeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVMNodeScrapeInformerWithOptions constructs a new informer for VMNodeScrape type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMNodeScrapeInformerWithOptions]).
func NewVMNodeScrapeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVMNodeScrapeInformerWithOptions(client, namespace, options)
}

// NewTypedVMNodeScrapeInformerWithOptions constructs a new informer for VMNodeScrape type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMNodeScrapeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VMNodeScrapeIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1beta1", Resource: "vmnodescrapes"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMNodeScrape](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMNodeScrapes(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMNodeScrapes(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMNodeScrapes(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMNodeScrapes(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1beta1.VMNodeScrape{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vMNodeScrapeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVMNodeScrapeInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vMNodeScrapeInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vMNodeScrapeInformer) TypedInformer() VMNodeScrapeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMNodeScrape](f.factory.InformerFor(&apioperatorv1beta1.VMNodeScrape{}, f.defaultInformer))
}

func (f *vMNodeScrapeInformer) Lister() operatorv1beta1.VMNodeScrapeLister {
	return operatorv1beta1.NewVMNodeScrapeLister(f.Informer().GetIndexer())
}

// ToTypedVMNodeScrapeInformer converts an untyped informer into a TypedVMNodeScrapeInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMNodeScrape. If that is not the case, calling type-safe methods of the returned
// TypedVMNodeScrapeInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVMNodeScrapeInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVMNodeScrapeInformer(informer VMNodeScrapeInformer) TypedVMNodeScrapeInformer {
	if informer, ok := informer.(TypedVMNodeScrapeInformer); ok {
		return informer
	}
	return &vMNodeScrapeTypedInformerAdapter{informer}
}

type vMNodeScrapeTypedInformerAdapter struct {
	VMNodeScrapeInformer
}

func (a *vMNodeScrapeTypedInformerAdapter) TypedInformer() VMNodeScrapeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMNodeScrape](a.Informer())
}

// ToVMNodeScrapeIndexInformer converts an untyped informer into a VMNodeScrapeIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMNodeScrape. If that is not the case, calling type-safe methods of the returned
// VMNodeScrapeIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VMNodeScrapeIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVMNodeScrapeIndexInformer(informer cache.SharedIndexInformer) VMNodeScrapeIndexInformer {
	if informer, ok := informer.(VMNodeScrapeIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMNodeScrape](informer)
}
