/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1beta1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMScrapeConfigInformer provides access to a shared informer and lister for
// VMScrapeConfigs. Prefer using the type-safe variant (see [TypedVMScrapeConfigInformer]).
type VMScrapeConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1beta1.VMScrapeConfigLister
}

// TypedVMScrapeConfigInformer provides access to a shared informer and lister for
// VMScrapeConfigs, including the type-safe TypedInformer variant.
// It is a superset of VMScrapeConfigInformer.
type TypedVMScrapeConfigInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VMScrapeConfigIndexInformer
	Lister() operatorv1beta1.VMScrapeConfigLister
}

// VMScrapeConfigIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VMScrapeConfigIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1beta1.VMScrapeConfig]

// VMScrapeConfigHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VMScrapeConfig.
type VMScrapeConfigHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1beta1.VMScrapeConfig]

// VMScrapeConfigDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VMScrapeConfig.
type VMScrapeConfigDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1beta1.VMScrapeConfig]

// VMScrapeConfigFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VMScrapeConfig.
type VMScrapeConfigFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1beta1.VMScrapeConfig]

// VMScrapeConfigIndexers is a specialization of [cache.TypedIndexers] for VMScrapeConfig.
type VMScrapeConfigIndexers = cache.TypedIndexers[*apioperatorv1beta1.VMScrapeConfig]

// DeletedVMScrapeConfig is a specialization of [cache.DeletedObject] for VMScrapeConfig.
type DeletedVMScrapeConfig = cache.DeletedObject[*apioperatorv1beta1.VMScrapeConfig]

type vMScrapeConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMScrapeConfigInformer constructs a new informer for VMScrapeConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMScrapeConfigInformer]).
func NewVMScrapeConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVMScrapeConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVMScrapeConfigInformer constructs a new informer for VMScrapeConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMScrapeConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMScrapeConfigIndexers) VMScrapeConfigIndexInformer {
	return NewTypedVMScrapeConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVMScrapeConfigInformer constructs a new informer for VMScrapeConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVMScrapeConfigInformer]).
func NewFilteredVMScrapeConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVMScrapeConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVMScrapeConfigInformer constructs a new informer for VMScrapeConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVMScrapeConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMScrapeConfigIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VMScrapeConfigIndexInformer {
	return NewTypedVMScrapeConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVMScrapeConfigInformerWithOptions constructs a new informer for VMScrapeConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMScrapeConfigInformerWithOptions]).
func NewVMScrapeConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVMScrapeConfigInformerWithOptions(client, namespace, options)
}

// NewTypedVMScrapeConfigInformerWithOptions constructs a new informer for VMScrapeConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMScrapeConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VMScrapeConfigIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1beta1", Resource: "vmscrapeconfigs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMScrapeConfig](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMScrapeConfigs(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMScrapeConfigs(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMScrapeConfigs(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMScrapeConfigs(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1beta1.VMScrapeConfig{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vMScrapeConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVMScrapeConfigInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vMScrapeConfigInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vMScrapeConfigInformer) TypedInformer() VMScrapeConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMScrapeConfig](f.factory.InformerFor(&apioperatorv1beta1.VMScrapeConfig{}, f.defaultInformer))
}

func (f *vMScrapeConfigInformer) Lister() operatorv1beta1.VMScrapeConfigLister {
	return operatorv1beta1.NewVMScrapeConfigLister(f.Informer().GetIndexer())
}

// ToTypedVMScrapeConfigInformer converts an untyped informer into a TypedVMScrapeConfigInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMScrapeConfig. If that is not the case, calling type-safe methods of the returned
// TypedVMScrapeConfigInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVMScrapeConfigInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVMScrapeConfigInformer(informer VMScrapeConfigInformer) TypedVMScrapeConfigInformer {
	if informer, ok := informer.(TypedVMScrapeConfigInformer); ok {
		return informer
	}
	return &vMScrapeConfigTypedInformerAdapter{informer}
}

type vMScrapeConfigTypedInformerAdapter struct {
	VMScrapeConfigInformer
}

func (a *vMScrapeConfigTypedInformerAdapter) TypedInformer() VMScrapeConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMScrapeConfig](a.Informer())
}

// ToVMScrapeConfigIndexInformer converts an untyped informer into a VMScrapeConfigIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMScrapeConfig. If that is not the case, calling type-safe methods of the returned
// VMScrapeConfigIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VMScrapeConfigIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVMScrapeConfigIndexInformer(informer cache.SharedIndexInformer) VMScrapeConfigIndexInformer {
	if informer, ok := informer.(VMScrapeConfigIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMScrapeConfig](informer)
}
