/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen-v0.37. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	internalinterfaces "github.com/VictoriaMetrics/operator/api/client/informers/externalversions/internalinterfaces"
	operatorv1beta1 "github.com/VictoriaMetrics/operator/api/client/listers/operator/v1beta1"
	versioned "github.com/VictoriaMetrics/operator/api/client/versioned"
	apioperatorv1beta1 "github.com/VictoriaMetrics/operator/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMSingleInformer provides access to a shared informer and lister for
// VMSingles. Prefer using the type-safe variant (see [TypedVMSingleInformer]).
type VMSingleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1beta1.VMSingleLister
}

// TypedVMSingleInformer provides access to a shared informer and lister for
// VMSingles, including the type-safe TypedInformer variant.
// It is a superset of VMSingleInformer.
type TypedVMSingleInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VMSingleIndexInformer
	Lister() operatorv1beta1.VMSingleLister
}

// VMSingleIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VMSingleIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1beta1.VMSingle]

// VMSingleHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VMSingle.
type VMSingleHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1beta1.VMSingle]

// VMSingleDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VMSingle.
type VMSingleDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1beta1.VMSingle]

// VMSingleFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VMSingle.
type VMSingleFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1beta1.VMSingle]

// VMSingleIndexers is a specialization of [cache.TypedIndexers] for VMSingle.
type VMSingleIndexers = cache.TypedIndexers[*apioperatorv1beta1.VMSingle]

// DeletedVMSingle is a specialization of [cache.DeletedObject] for VMSingle.
type DeletedVMSingle = cache.DeletedObject[*apioperatorv1beta1.VMSingle]

type vMSingleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMSingleInformer constructs a new informer for VMSingle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMSingleInformer]).
func NewVMSingleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVMSingleInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVMSingleInformer constructs a new informer for VMSingle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMSingleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMSingleIndexers) VMSingleIndexInformer {
	return NewTypedVMSingleInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVMSingleInformer constructs a new informer for VMSingle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVMSingleInformer]).
func NewFilteredVMSingleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVMSingleInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVMSingleInformer constructs a new informer for VMSingle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVMSingleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VMSingleIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VMSingleIndexInformer {
	return NewTypedVMSingleInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVMSingleInformerWithOptions constructs a new informer for VMSingle type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVMSingleInformerWithOptions]).
func NewVMSingleInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVMSingleInformerWithOptions(client, namespace, options)
}

// NewTypedVMSingleInformerWithOptions constructs a new informer for VMSingle type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVMSingleInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VMSingleIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator", Version: "v1beta1", Resource: "vmsingles"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMSingle](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMSingles(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMSingles(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMSingles(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1beta1().VMSingles(namespace).Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1beta1.VMSingle{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *vMSingleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVMSingleInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *vMSingleInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *vMSingleInformer) TypedInformer() VMSingleIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMSingle](f.factory.InformerFor(&apioperatorv1beta1.VMSingle{}, f.defaultInformer))
}

func (f *vMSingleInformer) Lister() operatorv1beta1.VMSingleLister {
	return operatorv1beta1.NewVMSingleLister(f.Informer().GetIndexer())
}

// ToTypedVMSingleInformer converts an untyped informer into a TypedVMSingleInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMSingle. If that is not the case, calling type-safe methods of the returned
// TypedVMSingleInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVMSingleInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVMSingleInformer(informer VMSingleInformer) TypedVMSingleInformer {
	if informer, ok := informer.(TypedVMSingleInformer); ok {
		return informer
	}
	return &vMSingleTypedInformerAdapter{informer}
}

type vMSingleTypedInformerAdapter struct {
	VMSingleInformer
}

func (a *vMSingleTypedInformerAdapter) TypedInformer() VMSingleIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMSingle](a.Informer())
}

// ToVMSingleIndexInformer converts an untyped informer into a VMSingleIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VMSingle. If that is not the case, calling type-safe methods of the returned
// VMSingleIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VMSingleIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVMSingleIndexInformer(informer cache.SharedIndexInformer) VMSingleIndexInformer {
	if informer, ok := informer.(VMSingleIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1beta1.VMSingle](informer)
}
